encyclopedia/urls.py
from django.urls import path, include
from . import views

app_name = 'encyclo'

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:entry>", views.content, name="content"),
    path("encyclopedia/new.html", views.new, name="new"),
    path("encyclopedia/edit.html", views.edit, name="edit"),
    path("encyclopedia/save", views.save, name="save"),
    path("encyclopedia/random", views.rand, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
from markdown2 import Markdown
import random

from . import util


def index(request):
    if request.method == "POST":
        query = request.POST['q']
        if query in util.list_entries():
            return render(request, "encyclopedia/content.html", {
                "content": convert_to_html(query),
                "title": query
            })
        else:
            l = util.list_entries()
            display = []
            for i in l:
                for j in query:
                    if j.lower() in i.lower():
                        if i not in display:
                            display.append(i)
            if display != []:
                return render(request, "encyclopedia/results.html", {
                    "entries": display,
                    "value":query
                })
            else:
                return render(request, "encyclopedia/error.html", {
                    "value": query,
                    "message": "does not exists"
                })
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })
    
def content(request, entry):
    if request.method == "POST":
        query = request.POST['q']
        if query in util.list_entries():
            return render(request, "encyclopedia/content.html", {
                "content": convert_to_html(query),
                "title": query
            })
        else:
            l = util.list_entries()
            display = []
            for i in l:
                for j in query:
                    if j.lower() in i.lower():
                        if i not in display:
                            display.append(i)
            if display != []:
                display = set(display)
                return render(request, "encyclopedia/results.html", {
                    "entries": display ,
                    "value" : query
                })
            else:
                return render(request, "encyclopedia/error.html", {
                    "value":query,
                    "message": "does not exists"
                })
                
    else:    
        if util.get_entry(entry):
            return render(request, "encyclopedia/content.html", {
                "content": convert_to_html(entry),
                "title" : entry
            })
        else:
            return render(request, "encyclopedia/error.html", {
                "value":entry,
                "message": "does not exists"
            })
        
def convert_to_html(title):
    content = util.get_entry(title)
    mark = Markdown()
    if content == None:
        return None
    else:
        return mark.convert(content)
        
class newform(forms.Form):
    title = forms.CharField(max_length=20, label='Title', widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={ 'class':'form-control', 'id':'exampleFormControlTextarea1', 'rows':'5'}))
        
def new(request):
    if request.method == 'POST':
        form = newform(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
        exists = util.get_entry(title)
        if exists != None:
            return render(request, "encyclopedia/error.html", {
                "value" : title,
                "message": "already exists"
            })
        else:
            util.save_entry(title, content)
            return render(request, "encyclopedia/content.html", {
                'title': title,
                'content': content
            })
    return render(request, "encyclopedia/new.html", {
        "form" : newform
    })
    
def edit(request):
    if request.method =="POST":
        title = request.POST['title']
        content = util.get_entry(title)
        form = newform()
        form.fields['title'].initial = title
        form.fields['content'].initial = content
        return render(request, "encyclopedia/edit.html", {
            "form" : form
        })
        
def save(request):
    if request.method == 'POST':
        form = newform(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            util.save_entry(title, content)
        return render(request, 'encyclopedia/content.html', {
            'title': title,
            'content': convert_to_html(title)
        })
        
def rand(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    url = '/{}'.format(random_entry)
    return HttpResponseRedirect(url)

encyclopedia/templates/encyclopedia/content.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
<form method="post" action="{% url 'encyclo:edit' %}">
    {% csrf_token %}
    <input type="hidden" name="title" value="{{title}}">
    <p><h1 style="color:gray; font-size:"> {{title}} </h1> <button type="submit" class="btn btn-outline-info">Edit</button></p>
    
</form>
<hr>

{{content|safe}}

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Enter Details</h1>
    <br/><br/>
    <div class="mb-3">
    <form method="post" action={% url 'encyclo:save'%}>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-outline-success">Save</button>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error!</h1>

    <p>{{value}} {{message}}</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclo:content' entry %}">{{ entry }}</a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method='post'>
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclo:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url "encyclo:new" %}"">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclo:random' %}"">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h1>Enter Details</h1>
    <br/><br/>
    <div class="mb-3">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-outline-success">Submit</button>
    </div>

{% endblock %}
  

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Possible Results
{% endblock %}

{% block body %}
    <h1>Are you looking for any of these</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclo:content' entry %}">{{ entry }}</a>
        {% endfor %}
    </ul>
    <a href= "{{value}}">none of these</a>
{% endblock %}